/* TABLES */

CREATE TABLE user (
uid INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
fname VARCHAR(50) NOT NULL,
lname VARCHAR(50),
email VARCHAR(50) NOT NULL,
passwd VARCHAR(50) NOT NULL
);

CREATE TABLE post (
post_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
uid INT NOT NULL,
title VARCHAR(255) NOT NULL,
date DATE NOT NULL,
body TEXT
);

CREATE TABLE post_summary(
ps_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
post_id INT NOT NULL,
summary TEXT(400),
poster TEXT(300)
);

CREATE TABLE post_views(
post_id INT NOT NULL UNIQUE,
view_count INT DEFAULT 0,
title VARCHAR(255) NOT NULL
);